#!/bin/bash
#
# @file    casicsdb
# @brief   start/stop/restart script for ZEO database for CASICS
# @author  Michael Hucka
#
# Most of this script came from this answer to a Stack Overflow question:
#   http://stackoverflow.com/a/17686989/743730
# Code contributed to Stack Overflow is licensed CC-BY-SA 3.0.
# https://creativecommons.org/licenses/by-sa/3.0/

service_name="CASICS database server"
directory=$(dirname ${0##*/})
start_script="$directory/startserver.py"
pid_file="$directory/server.pid"
log_file="server.log"
process_name="runzeo.py"

# Returns a boolean and optionally the pid
running() {
    local status=false
    if [[ -f $pid_file ]]; then
        # check to see it corresponds to the running script
        local pid=$(< "$pid_file")
        local cmdline=/proc/$pid/cmdline
        # you may need to adjust the regexp in the grep command
        if [[ -f $cmdline ]] && grep -qi $process_name $cmdline; then
            status="true $pid"
        fi
    fi
    echo $status
}

start() {
    echo "Starting $service_name"
    nohup "$start_script" > $log_file 2>&1 &
    echo $! > "$pid_file"
}

stop() {
    # `kill -0 pid` returns successfully if the pid is running, but does not
    # actually kill it.
    kill -0 $1 && kill $1
    rm "$pid_file"
    echo "stopped"
}

read running pid < <(running)

case $1 in 
    start)
        if $running; then
            echo "$service_name is already running with PID $pid"
        else
            start
        fi
        ;;
    stop)
        stop $pid
        ;;
    restart)
        stop $pid
        start
        ;;
    status)
        if $running; then
            echo "$service_name is running with PID $pid"
        else
            echo "$service_name is not running"
        fi
        ;;
    *)  echo "usage: $0 <start|stop|restart|status>"
        exit
        ;;
esac
